name: ssh_mobile

packages:
  - apps/ssh_mobile_full
  - packages/core/app_core
  - packages/core/app_ui
  - packages/core/connection_core
  - packages/features/feature_connection
  - packages/features/feature_monitoring
  - packages/features/feature_system_admin
  - packages/features/feature_playbook
  - packages/features/feature_sftp
  - packages/features/feature_terminal
  - packages/features/feature_lan_share
  - packages/infrastructure/network_transport
  - packages/infrastructure/ssh_core
  - packages/infrastructure/ssh_mobile_network_native

scripts:
  format: dart format --output=none --set-exit-if-changed .
  analyze: dart analyze .
  test: dart test
