name: ssh_mobile
description: Mobile SSH client
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dartssh2: any
  xterm:
    path: third_party/xterm
  flutter_background_service: any
  flutter_local_notifications: any
  flutter_secure_storage: any
  provider: any
  shared_preferences: any
  path_provider: any
  uuid: any
  intl: any
  path: any
  permission_handler: any
  cryptography: any
  file_picker: ^12.0.0-beta.7
  flutter_markdown: any
  webview_flutter: any
  printing: any
  fl_chart: any
  animations: any
  drift: any
  drift_flutter: any
  sqlite3_flutter_libs: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  build_runner: any
  drift_dev: any

flutter:
  uses-material-design: true
  assets:
    - assets/
