name: _
publish_to: none

environment:
  sdk: ^3.12.0

workspace:
  - apps/ssh_mobile_full
  - packages/core/app_core
  - packages/core/connection_core
  - packages/features/feature_connection
  - packages/infrastructure/network_transport
  - packages/infrastructure/ssh_mobile_network_native

dev_dependencies:
  melos: ^8.2.2
